server:
  port: 4343
spring:
  application:
    name: rest-api-for-task-management

  datasource:
    url: jdbc:h2:./db/taskService;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: false

  liquibase:
    change-log: classpath:/db/changelog/master.yml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true

  data:
    redis:
      port: 6379
      host: localhost

  mail:
    host: smtp.gmail.com
    username: basit.03.kg@gmail.com
    password: lppl cibr qxsm dmgd
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate: WARN
    root: info