INSERT INTO TASKS (TITLE, DESCRIPTION, STATUS, CREATED_AT, UPDATED_AT)
VALUES
    ('Task 1', 'Description of Task 1', 'NEW', NOW(), NOW()),
    ('Task 2', 'Description of Task 2', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 3', 'Description of Task 3', 'COMPLETED', NOW(), NOW()),
    ('Task 4', 'Description of Task 4', 'NEW', NOW(), NOW()),
    ('Task 5', 'Description of Task 5', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 6', 'Description of Task 6', 'COMPLETED', NOW(), NOW()),
    ('Task 7', 'Description of Task 7', 'NEW', NOW(), NOW()),
    ('Task 8', 'Description of Task 8', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 9', 'Description of Task 9', 'COMPLETED', NOW(), NOW()),
    ('Task 10', 'Description of Task 10', 'NEW', NOW(), NOW()),
    ('Task 11', 'Description of Task 11', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 12', 'Description of Task 12', 'COMPLETED', NOW(), NOW()),
    ('Task 13', 'Description of Task 13', 'NEW', NOW(), NOW()),
    ('Task 14', 'Description of Task 14', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 15', 'Description of Task 15', 'COMPLETED', NOW(), NOW()),
    ('Task 16', 'Description of Task 16', 'NEW', NOW(), NOW()),
    ('Task 17', 'Description of Task 17', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 18', 'Description of Task 18', 'COMPLETED', NOW(), NOW()),
    ('Task 19', 'Description of Task 19', 'NEW', NOW(), NOW()),
    ('Task 20', 'Description of Task 20', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 21', 'Description of Task 21', 'COMPLETED', NOW(), NOW()),
    ('Task 22', 'Description of Task 22', 'NEW', NOW(), NOW()),
    ('Task 23', 'Description of Task 23', 'IN_PROGRESS', NOW(), NOW()),
    ('Task 24', 'Description of Task 24', 'COMPLETED', NOW(), NOW()),
    ('Task 25', 'Description of Task 25', 'NEW', NOW(), NOW());